# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: uep.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'uep.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tuep.proto\x12\x12uep_core.protocols\"\xb0\x01\n\nUEPRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x12>\n\x08metadata\x18\x04 \x03(\x0b\x32,.uep_core.protocols.UEPRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xb3\x01\n\x0bUEPResponse\x12\x13\n\x0bresponse_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x12?\n\x08metadata\x18\x04 \x03(\x0b\x32-.uep_core.protocols.UEPResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"S\n\x11ModelRegistration\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x04 \x01(\t2\x85\x02\n\x12UEPExchangeService\x12W\n\rRegisterModel\x12%.uep_core.protocols.ModelRegistration\x1a\x1f.uep_core.protocols.UEPResponse\x12G\n\x04Send\x12\x1e.uep_core.protocols.UEPRequest\x1a\x1f.uep_core.protocols.UEPResponse\x12M\n\x06Stream\x12\x1e.uep_core.protocols.UEPRequest\x1a\x1f.uep_core.protocols.UEPResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uep_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UEPREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_UEPREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_UEPRESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_UEPRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_UEPREQUEST']._serialized_start=34
  _globals['_UEPREQUEST']._serialized_end=210
  _globals['_UEPREQUEST_METADATAENTRY']._serialized_start=163
  _globals['_UEPREQUEST_METADATAENTRY']._serialized_end=210
  _globals['_UEPRESPONSE']._serialized_start=213
  _globals['_UEPRESPONSE']._serialized_end=392
  _globals['_UEPRESPONSE_METADATAENTRY']._serialized_start=163
  _globals['_UEPRESPONSE_METADATAENTRY']._serialized_end=210
  _globals['_MODELREGISTRATION']._serialized_start=394
  _globals['_MODELREGISTRATION']._serialized_end=477
  _globals['_UEPEXCHANGESERVICE']._serialized_start=480
  _globals['_UEPEXCHANGESERVICE']._serialized_end=741
# @@protoc_insertion_point(module_scope)
