# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import uep_pb2 as uep__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in uep_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UEPExchangeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterModel = channel.unary_unary(
                '/uep_core.protocols.UEPExchangeService/RegisterModel',
                request_serializer=uep__pb2.ModelRegistration.SerializeToString,
                response_deserializer=uep__pb2.UEPResponse.FromString,
                _registered_method=True)
        self.Send = channel.unary_unary(
                '/uep_core.protocols.UEPExchangeService/Send',
                request_serializer=uep__pb2.UEPRequest.SerializeToString,
                response_deserializer=uep__pb2.UEPResponse.FromString,
                _registered_method=True)
        self.Stream = channel.stream_stream(
                '/uep_core.protocols.UEPExchangeService/Stream',
                request_serializer=uep__pb2.UEPRequest.SerializeToString,
                response_deserializer=uep__pb2.UEPResponse.FromString,
                _registered_method=True)


class UEPExchangeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UEPExchangeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterModel,
                    request_deserializer=uep__pb2.ModelRegistration.FromString,
                    response_serializer=uep__pb2.UEPResponse.SerializeToString,
            ),
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=uep__pb2.UEPRequest.FromString,
                    response_serializer=uep__pb2.UEPResponse.SerializeToString,
            ),
            'Stream': grpc.stream_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=uep__pb2.UEPRequest.FromString,
                    response_serializer=uep__pb2.UEPResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uep_core.protocols.UEPExchangeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('uep_core.protocols.UEPExchangeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UEPExchangeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uep_core.protocols.UEPExchangeService/RegisterModel',
            uep__pb2.ModelRegistration.SerializeToString,
            uep__pb2.UEPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uep_core.protocols.UEPExchangeService/Send',
            uep__pb2.UEPRequest.SerializeToString,
            uep__pb2.UEPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/uep_core.protocols.UEPExchangeService/Stream',
            uep__pb2.UEPRequest.SerializeToString,
            uep__pb2.UEPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
